name: Release

on:
  release:
    types: [ published, edited ]
  push:
    branches: [ master ]
    paths:
      - 'contrib/docker/Dockerfile.release'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v3
      -
        name: set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: set up buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      -
        name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: build
        run: cd contrib/docker && ./build.sh release
